{% set name = "zstash" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/E3SM-Project/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 192f9842ce07168bdeaec78175bad88e974a6be5ca7680faa86258baef840f38

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6

test:
  imports:
    - zstash
  commands:
    - zstash --help

about:
  home: https://github.com/E3SM-Project/zstash

