{% set name = "zstash" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/E3SM-Project/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: d3e9d5530a1a2a35fa1a0c11a13b33e36eb24bd97fcae0945a43cb8c589eb8a7

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6

test:
  imports:
    - zstash
  commands:
    - zstash --help

about:
  home: https://github.com/E3SM-Project/zstash

