{% set name = "zstash" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/E3SM-Project/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 44d0607e4826792329c37cc68efc647ce78a0263a9f811319a343bd91e9d1d8e

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6

about:
  home: https://github.com/E3SM-Project/zstash

